name: hello

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  
jobs:
    hello:
      runs-on: ubuntu-latest
      steps: 
      - uses: action/checkout@v2
      - name: hello world
        run: echo "saif"
        shell: bash
      
      
